### ISSUE TITLE
Installation on Linux fails

### ISSUE THREAD

**Issue by peteruhrig** [EricWilbanks/faseAlign#13]
Dear all,

I have tried to install faseAlign on Ubuntu 16.04 LTS according to the docs. These are the issues I came across:
- when making HTK: /usr/include/features.h:367:25: fatal error: sys/cdefs.h: file or directory not found (resolved by running sudo apt-get install libc6-dev-i386)
- the installation of audiolabel is only described in the instructions for macOS, but not for Linux
- After installing audiolabel, the installation of faseAlign still fails:

```
puhrig@vm273:~$ pip3 install git+git://github.com/EricWilbanks/faseAlign --upgrade
Collecting git+git://github.com/EricWilbanks/faseAlign
  Cloning git://github.com/EricWilbanks/faseAlign to /tmp/pip-4hbfa98c-build
Collecting sox (from faseAlign===1.1.9)
  Downloading https://files.pythonhosted.org/packages/ba/0d/332b12c582deed0688f4e1b3b0d6b0ef3bc51f06500ce25a32546801ec15/sox-1.3.3-py2.py3-none-any.whl
Collecting audiolabel (from faseAlign===1.1.9)
  Could not find a version that satisfies the requirement audiolabel (from faseAlign===1.1.9) (from versions: )
No matching distribution found for audiolabel (from faseAlign===1.1.9)
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

puhrig@vm273:~$ pip3 install git+git://github.com/rsprouse/audiolabel
Collecting git+git://github.com/rsprouse/audiolabel
  Cloning git://github.com/rsprouse/audiolabel to /tmp/pip-1h9jv21s-build
Installing collected packages: audiolabel
  Running setup.py install for audiolabel ... done
Successfully installed audiolabel-0.0.0
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

puhrig@vm273:~$ pip3 install git+git://github.com/EricWilbanks/faseAlign --upgrade
Collecting git+git://github.com/EricWilbanks/faseAlign
  Cloning git://github.com/EricWilbanks/faseAlign to /tmp/pip-80msgr88-build
Collecting sox (from faseAlign===1.1.9)
  Using cached https://files.pythonhosted.org/packages/ba/0d/332b12c582deed0688f4e1b3b0d6b0ef3bc51f06500ce25a32546801ec15/sox-1.3.3-py2.py3-none-any.whl
Collecting audiolabel (from faseAlign===1.1.9)
  Could not find a version that satisfies the requirement audiolabel (from faseAlign===1.1.9) (from versions: )
No matching distribution found for audiolabel (from faseAlign===1.1.9)
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
This is where I'm stuck now. I'd be grateful for any pointers!

Best wishes,
Peter

**Comment by EricWilbanks** [comment]
Hi Peter,

Thanks for this information! Because of how I was testing during my
development, I made an assumption that turned out not to be true about the
distribution of the audiolabel package.

Does the installation of faseAlign proceed better after you manually
install audiolabel using the following?

pip install git+git://github.com/rsprouse/audiolabel

I'll put it on my to-do list to update the documentation for installation
and hopefully change some of the dependency requirements so that
installation is smoother.

Cheers,
Eric

**Comment by peteruhrig** [comment]
Hi Eric,

thanks for getting back to me so fast! I tried with the line you gave me (both pip and pip3), and audiolabel says it installs (as in the output given above), but the installation of faseAlign still fails with the same message as given above.

**Comment by EricWilbanks** [comment]
Hi Peter,

Sorry for the delay on this. I've made some changes with how the package is distributed in v. 1.1.10. If this is still an issue for you, could you try updating with the latest version and seeing if the result is any different?

I suspect your issue won't be resolve but we can use the most latest version as a starting place to identify the cause.

Thanks!

**Comment by peteruhrig** [comment]
Hi Eric,

Thanks for the update! These are the steps I needed:
```
sudo apt install sox
pip3 install git+git://github.com/rsprouse/audiolabel
pip3 install git+https://github.com/EricWilbanks/faseAlign.git --upgrade
```
It installs all right this time. Can't test whether it runs at the moment, though, because apparently my HTK credentials have expired or something like that, so I cannot download it.

Best,
Peter

**Comment by afperezm** [comment]
Installing 3.4.1 under Ubuntu 18.04.5 LTS I didn't encounter this problem, however I had to install 32-bit headers and libraries since HTK was built for 32 bits. I did that by installing the gcc-multilib package.

**Comment by EricWilbanks** [comment]
I've just outlined an updated installation process that should hopefully avoid package issues like this in the future. Please do open a new issue if you encounter one!
