### ISSUE TITLE
faseAlign: command not found

### ISSUE THREAD

**Issue by lauryswagner** [EricWilbanks/faseAlign#14]
Hi Eric,

I successfully installed faseAlign and all its dependencies (I believe), but my terminal doesn't recognize the faseAlign command when I attempt to use it. I re-started my virtual machine (using Ubuntu), but no luck.

Any suggestions would be appreciated!

**Comment by EricWilbanks** [comment]
Hi, sorry for the delay on this!

what is the output when you call `which faseAlign` and `locate faseAlign`?

Thanks!

**Comment by EricWilbanks** [comment]
We've just outlined a new installation process that should hopefully avoid issues with dependencies and package locations. Please feel free to open a new issue if you encounter another one!
