### ISSUE TITLE
Original audio file is replaced by downsampled version.

### ISSUE THREAD

**Issue by axme100** [EricWilbanks/faseAlign#5]
Hello,

I'm noticing that when running for example `faseAlign -w test.wav -t test.TextGrid` the original audio file is overwritten by the audio file that was downsampled by sox for alignment.

**Comment by EricWilbanks** [comment]
Hi There,

Thanks for the heads up. This is unintended behavior which I've fixed in the most recent version. You can get the bug fix by upgrading with pip:

`pip install git+git://github.com/EricWilbanks/faseAlign --upgrade`

Thanks again!

**Comment by axme100** [comment]
Thanks for fixing this!
